name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Setup Node
      uses: actions/setup-node@v1.4.1
      with:
        node-version: 10.x
    - name: Bump version and push tag
      id: bumpVersion
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.BUMP_TAGS_TOKEN }}
        WITH_V: true
    - name: New tag
      run: echo "${{ steps.bumpVersion.outputs.new_tag }}"
    # Restore cache
    - name: Restore node cache
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      run: npm install
    - name: Run build
      run:  npm run build
    - name: Docker Push
      uses: opspresso/action-docker@v0.2.8
      with:
        args: --docker
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERFILE: "Dockerfile"
        IMAGE_NAME: "osamaaamer/awesome-backend"
        TAG_NAME: "${{ steps.bumpVersion.outputs.new_tag }}"
        LATEST: "true"

